//! Diesel schema definitions for message persistence.
//!
//! This file is regenerated by `diesel print-schema`. Custom documentation
//! in the header is preserved via `diesel_schema_patch.rs` configured in
//! `diesel.toml`.
//!
//! Run `diesel migration run` after creating or modifying migrations,
//! then `diesel print-schema` to update this file.
//!
//! The schema follows corbusier-design.md §6.2.3 with JSONB storage for
//! flexible message content and metadata.
