//! Diesel schema definitions for message persistence.
//!
//! This file is generated by `diesel print-schema` and should not be modified
//! manually. Run `diesel migration run && diesel print-schema > src/message/adapters/schema.rs`
//! after creating or modifying migrations.
//!
//! The schema follows corbusier-design.md §6.2.3 with JSONB storage for
//! flexible message content and metadata.

diesel::table! {
    /// The `conversations` table stores conversation metadata.
    ///
    /// Conversations group related messages and provide context for
    /// agent interactions.
    conversations (id) {
        /// Unique conversation identifier.
        id -> Uuid,
        /// Optional reference to the associated task.
        task_id -> Nullable<Uuid>,
        /// Flexible context data stored as JSONB.
        context -> Jsonb,
        /// Conversation state: active, paused, or archived.
        #[max_length = 50]
        state -> Varchar,
        /// When the conversation was created.
        created_at -> Timestamptz,
        /// When the conversation was last updated.
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// The `messages` table stores conversation messages with append-only semantics.
    ///
    /// Messages are immutable after creation per corbusier-design.md F-001-RQ-002.
    messages (id) {
        /// Unique message identifier.
        id -> Uuid,
        /// Reference to the containing conversation.
        conversation_id -> Uuid,
        /// Message role: user, assistant, tool, or system.
        #[max_length = 20]
        role -> Varchar,
        /// Message content parts stored as JSONB array.
        content -> Jsonb,
        /// Message metadata including `agent_backend`, `turn_id`, etc.
        metadata -> Jsonb,
        /// When the message was created.
        created_at -> Timestamptz,
        /// Sequence number for ordering within the conversation.
        sequence_number -> Int8,
    }
}

diesel::table! {
    /// The `domain_events` table stores event sourcing records for audit trails.
    ///
    /// Provides comprehensive audit history per corbusier-design.md §6.2.3.4.
    domain_events (id) {
        /// Unique event identifier.
        id -> Uuid,
        /// The aggregate (entity) this event applies to.
        aggregate_id -> Uuid,
        /// Type of aggregate (e.g., "Message", "Conversation").
        #[max_length = 100]
        aggregate_type -> Varchar,
        /// Type of event (e.g., `MessageCreated`).
        #[max_length = 100]
        event_type -> Varchar,
        /// Event payload stored as JSONB.
        event_data -> Jsonb,
        /// Schema version for event evolution.
        event_version -> Int4,
        /// When the event occurred.
        occurred_at -> Timestamptz,
        /// Correlation ID for distributed tracing.
        correlation_id -> Nullable<Uuid>,
        /// Causation ID linking to triggering event.
        causation_id -> Nullable<Uuid>,
        /// User who caused the event.
        user_id -> Nullable<Uuid>,
        /// Session context.
        session_id -> Nullable<Uuid>,
    }
}

diesel::table! {
    /// The `audit_logs` table captures all database operations for compliance.
    ///
    /// Populated automatically by database triggers.
    audit_logs (id) {
        /// Unique audit log entry identifier.
        id -> Uuid,
        /// Name of the table that was modified.
        #[max_length = 100]
        table_name -> Varchar,
        /// Operation type: INSERT, UPDATE, or DELETE.
        #[max_length = 10]
        operation -> Varchar,
        /// Primary key of the affected row.
        row_id -> Nullable<Uuid>,
        /// Previous values (for UPDATE and DELETE).
        old_values -> Nullable<Jsonb>,
        /// New values (for INSERT and UPDATE).
        new_values -> Nullable<Jsonb>,
        /// User who performed the operation.
        user_id -> Nullable<Uuid>,
        /// Session context.
        session_id -> Nullable<Uuid>,
        /// Correlation ID for distributed tracing.
        correlation_id -> Nullable<Uuid>,
        /// Causation ID linking to triggering event.
        causation_id -> Nullable<Uuid>,
        /// Application that performed the operation.
        #[max_length = 100]
        application_name -> Nullable<Varchar>,
        /// When the operation occurred.
        occurred_at -> Timestamptz,
    }
}

diesel::joinable!(messages -> conversations (conversation_id));

diesel::allow_tables_to_appear_in_same_query!(audit_logs, conversations, domain_events, messages,);
