//! Message role types defining the source of a message in a conversation.

use serde::{Deserialize, Serialize};
use std::fmt;

/// The role of a message participant in a conversation.
///
/// Corbusier uses four roles to classify message sources, enabling consistent
/// handling across different agent backends.
///
/// # Examples
///
/// ```
/// use corbusier::message::domain::Role;
///
/// let role = Role::Assistant;
/// assert!(role.can_call_tools());
/// assert!(!role.is_human());
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// A message from a human user.
    User,
    /// A message generated by an AI assistant.
    Assistant,
    /// A message containing tool execution results.
    Tool,
    /// A system-level message (prompts, context, instructions).
    System,
}

impl fmt::Display for Role {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::User => write!(f, "user"),
            Self::Assistant => write!(f, "assistant"),
            Self::Tool => write!(f, "tool"),
            Self::System => write!(f, "system"),
        }
    }
}

impl Role {
    /// Returns `true` if this role can initiate tool calls.
    ///
    /// Only assistant messages may contain tool call requests.
    #[must_use]
    pub const fn can_call_tools(&self) -> bool {
        matches!(self, Self::Assistant)
    }

    /// Returns `true` if this role represents a human participant.
    #[must_use]
    pub const fn is_human(&self) -> bool {
        matches!(self, Self::User)
    }

    /// Returns `true` if this role represents system-level content.
    #[must_use]
    pub const fn is_system(&self) -> bool {
        matches!(self, Self::System)
    }

    /// Returns `true` if this role represents tool output.
    #[must_use]
    pub const fn is_tool(&self) -> bool {
        matches!(self, Self::Tool)
    }
}
