{{- if .Values.externalSecret.enabled -}}
{{- $storeRef := .Values.externalSecret.secretStoreRef -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ default (include "corbusier.fullname" .) .Values.externalSecret.targetName }}
  labels:
    {{- include "corbusier.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ $storeRef.name | quote }}
    kind: {{ $storeRef.kind | quote }}
  target:
    name: {{ default (include "corbusier.fullname" .) .Values.externalSecret.targetName }}
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
